### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by HellandB** [felipefrancisco/pokemon-go-map#1]
Great app mate! I got some questions.

Is it possible to delete a mark? (if you create a mark by an error)

Is it possible to create a mark inside another mark? (Two pokemons spawn in the same area)

Maybe it should be possible add some meta-data to the marks, I.E if how often the pokemon spawns etc.

I can not get the search to work. I do not live in Ireland, and thus have to scroll out and move the page every time I open it.

A search for pokemons, I.E If I  want to find a Rattata, it should be possible to search for spots where it has been marked.

Cheers!

**Comment by felipefrancisco** [comment]
Hey, 

Yes, you can delete your own pokemon.
Also, I'm developing a "Reporting" system, so users can report false pokemon markers.

It's not possible to create a mark inside a circle (yet).

I'm working on meta-data and G+ login right now, probably it will be live on a few hours.

The maps now focus on your country by default (and you can now use the search, as well, there was a bug on the Google Places API integration).

Search for pokemon will be done as soon as I finish the G+ login system.

I loved all suggestions, thanks a lot!

Thanks for all the support! :)

**Comment by felipefrancisco** [comment]
Reporting System is live.
Circle overlapping is live.
Map focus by default on your country now.

Thanks for suggestions and support!
