### ISSUE TITLE
"Loading" missing

### ISSUE THREAD

**Issue by pablohpsilva** [felipefrancisco/pokemon-go-map#10]
I believe its a "loading" image. It's not showing, like you can see in the image:

<img width="887" alt="screen shot 2016-07-16 at 2 25 03 pm" src="https://cloud.githubusercontent.com/assets/2090635/16896103/7c59fb0e-4b60-11e6-966f-7964d0c91711.png">

**Comment by felipefrancisco** [comment]
![image](https://cloud.githubusercontent.com/assets/2165248/16896247/087d319e-4b86-11e6-899c-03ff90231d05.png)

It seems to be working here. Are you still receiving this error image?

**Comment by pablohpsilva** [comment]
I found this (check the url):
<img width="772" alt="screen shot 2016-07-16 at 3 19 02 pm" src="https://cloud.githubusercontent.com/assets/2090635/16896378/f278d736-4b67-11e6-84b7-1d4f9adf2490.png">

**Comment by felipefrancisco** [comment]
The S3 bucket policy seems to be correct, but I've updated it and added the static domain anyway, can you please try again? Hope it's solved now :)
