### ISSUE TITLE
Suggestion: Add some kind of global rarity percentage to the map

### ISSUE THREAD

**Issue by bmarshall645** [felipefrancisco/pokemon-go-map#11]
Maybe add some kind of global rarity percentage? As pokemon get added you can see specific info for how rare that pokemon is and how many sightings have been reported for it.

**Comment by felipefrancisco** [comment]
@bmarshall645 can you please send me your e-mail? I'd like to talk with you on private.

**Comment by bmarshall645** [comment]
@felipefrancisco Anyway to private msg or anything? I dont feel comfortable giving out my email.
