### ISSUE TITLE
Bug? Can't remove pokemon from map

### ISSUE THREAD

**Issue by bmarshall645** [felipefrancisco/pokemon-go-map#12]
So I am logged in with google and for some reason I can't remove pokemon on the map. I click the remove pokemon and nothing happens.

**Comment by felipefrancisco** [comment]
I was deploying the reporting system, now the issue is fixed. Can you check it again, please?

**Comment by bmarshall645** [comment]
Can you remove all the ones placed on Ayer, MA I am gonna redo it sense you added the overlapping circles. Can you make it possible to remove the pokeball markers? Sometimes I accidentally put one down when moving around the map.

**Comment by felipefrancisco** [comment]
The Pokeball marker is not saved at all, don't worry.
I'm cleaning the Ayer area now, hope it helps
