### ISSUE TITLE
Add an url for map defined location

### ISSUE THREAD

**Issue by plasmahawk** [felipefrancisco/pokemon-go-map#13]
Hi Felipe Awesome project and awesome idea, can you add a share location URL to the map, so I can save it and jump to the location automaticaly. Much like you can share a google map location by sending the URL with the coordinates and zoom level this would let me quickly jump to my neighborhood. or a Locate me button which would tie into location sevrvices and center the map on my position,.

thx!!

**Comment by felipefrancisco** [comment]
Great suggestion. I'll add a "saved location" feature first, then I'll focus on the URLs ;)

**Comment by felipefrancisco** [comment]
@plasmahawk Hey there, check out the new "My Locations" feature. Do you think the URLs are still required? Let me know what you think about it :)

**Comment by plasmahawk** [comment]
Hi Felipe, My location now works! Looks awesome, It would be cool if I can send a location screen of where I am going or what I saw to a group. For example if you are in new your and you want to send a location in brooklyn . Current window location .. current view location would be great. Thank you good sir!

**Comment by felipefrancisco** [comment]
Transforming this issue into an official task.

**Comment by poke23** [comment]
Thanks a lot. [pokemon go hack](http://pokemongohacker.net)
