### ISSUE TITLE
Suggestion: Add a description option under pokemon

### ISSUE THREAD

**Issue by beefung** [felipefrancisco/pokemon-go-map#14]
So I've been looking through a few different mapping websites and have found yours to be the easiest to add pokemon and also most used in my area of living. I think though you should be able to add a description underneath a pokemon sighting to include

time
sighting / confirmed capture

This would make the website that much more descriptive and validate a lot of spots b/c as of rn people can really just put anything down

**Comment by felipefrancisco** [comment]
Thanks for support, mate! :)

This is a great suggestion, I'll add this to the backlog, then I can focus on them after I finish some major stuff like filtering and pokestops/gyms placement.
