### ISSUE TITLE
Bug: Text & Social icons going outside the white "Welcome Trainer" box

### ISSUE THREAD

**Issue by bmarshall645** [felipefrancisco/pokemon-go-map#15]
So when I reload the page and the Welcome Trainer box comes up some of the text and stuff goes outside the box.

http://imgur.com/a/cZPKP

**Comment by felipefrancisco** [comment]
I should be seeing the phone view, not the pc view :o
What's this phone?

**Comment by bmarshall645** [comment]
@felipefrancisco This was on my windows laptop. The screenshot I did with gyazo was cropped.

**Comment by felipefrancisco** [comment]
@bmarshall645 oh, can you send me regular screenshot of the page, please? just click print screen and press ctrl+v here in the comment box, the upload is automatic

**Comment by bmarshall645** [comment]
![image](https://cloud.githubusercontent.com/assets/20467126/16902616/9372e206-4c32-11e6-8d88-5012ad08b245.png)

**Comment by felipefrancisco** [comment]
Thanks buddy :)

**Comment by felipefrancisco** [comment]
@bmarshall645 fixed!
