### ISSUE TITLE
Bug?: Saved Locations not there after page refresh

### ISSUE THREAD

**Issue by bmarshall645** [felipefrancisco/pokemon-go-map#16]
I don't know if this is a bug or not but I saved some locations to My Locations and after I refreshed the page they were no longer there.

**Comment by felipefrancisco** [comment]
I was deploying some stuff to the server, sorry about that. Can you please try again, please? let me know if they are still vanishing

**Comment by bmarshall645** [comment]
@felipefrancisco Still disappearing

**Comment by felipefrancisco** [comment]
@bmarshall645 your place was logged on the database:
28  417 Ayer, MA    2016-07-17 19:14:11 2016-07-17 19:14:11

Maybe the api is with a problem.
Did you register using facebook, google or both?

**Comment by felipefrancisco** [comment]
OH, I see the problem now, will fix it

**Comment by felipefrancisco** [comment]
@bmarshall645 try it now again, please

**Comment by bmarshall645** [comment]
@felipefrancisco All set

**Comment by felipefrancisco** [comment]
@bmarshall645 what this means? HAHAH sorry, I'm not a native english speaker :(

**Comment by bmarshall645** [comment]
@felipefrancisco Just means that it works and the problem is fixed :)

**Comment by felipefrancisco** [comment]
@bmarshall645 oooooh, nice! thanks for helping me on this (again) hahah
