### ISSUE TITLE
Question about placing Pokemon locations

### ISSUE THREAD

**Issue by RoombaCat** [felipefrancisco/pokemon-go-map#17]
When leaving a spawn location of a Pokemon, are only Pokemon that have spawned multiple times in the same location to be counted/considered?

I visit a park near my house frequently that will always spawn Meowths and Eevees, so that would make sense to report it, something that I have seen in the same area on multiple occasions.

What if I am to encounter a more rare Pokemon in that area once? Say a group of my friends and myself all visit an area and a Pinsir spawns, and we all see it, yet this is the first of a Pinsir we have seen in this area, and now I have yet to see another since then at the location. Should I mark it if multiple devices saw the Pokemon, or does that not entirely matter?

What I'm trying to ask is how often should you report a Pokemon being found, whenever its found or only when it's seen multiple times?

AWESOME map by the way, already using it daily, can't wait to see what comes next!

Thank you!

**Comment by felipefrancisco** [comment]
Hey, thanks getting some time to drop a message here :)

If a Pokémon spawn on any location, it should be added to map only once on that location, the reason for this is that I'm planning to  add a frequency indicator to the markers.

About the Pinsir question, I think 2nd tier and 3rd tier Pokémon are more likely to appear to higher level players, so, I'm still trying to figure out what would be the best way to solve this situation on the map, so players won't mark this Pinsir as "seen multiple times" haha. Do you have any suggestions?

Cheers! Thanks for your support :)

**Comment by felipefrancisco** [comment]
@RoombaCat  Hey, thanks getting some time to drop a message here :)

If a Pokémon spawn on any location, it should be added to map only once on that location, the reason for this is that I'm planning to  add a frequency indicator to the markers.

About the Pinsir question, I think 2nd tier and 3rd tier Pokémon are more likely to appear to higher level players, so, I'm still trying to figure out what would be the best way to solve this situation on the map, so players won't mark this Pinsir as "seen multiple times" haha. Do you have any suggestions?

Cheers! Thanks for your support :)

**Comment by RoombaCat** [comment]
I have multiple suggestions, and I know some have been said but I'll list them out here

- Reporting Pokemon seen at what level and filtering map by level

**Comment by nyeung01** [comment]
Should we also consider lured Pokemon as well? So far, I haven't included any lured ones on the map because normally they won't appear unless there's a lured module.
