### ISSUE TITLE
Data dump functionality

### ISSUE THREAD

**Issue by thomasjungblut** [felipefrancisco/pokemon-go-map#27]
Do you plan on adding a data dump? I think a lot of people would like to get their hands dirty with some data mining on the amount of data you've collected. It's probably also worth considering to submit this as a playground project to Kaggle later once the data quality is a bit better.

Maybe a simple idea would be akin to the daily wikipedia data dump. Simply a dump of a SQL table as csv or so would be enough for most of us ;)

**Comment by felipefrancisco** [comment]
Hey, Thomas. Sorry, data dumping is restricted at the moment, I'm studying the best way to publish this data. What's this Kaggle? Never heard of it before
