### ISSUE TITLE
Reporting sitings/nests

### ISSUE THREAD

**Issue by BMOv2600** [felipefrancisco/pokemon-go-map#29]
Do users have to be moderators in order to post sightings? 

[Fryman Canyon](https://www.google.com/maps/place/34%C2%B008'01.7%22N+118%C2%B023'31.4%22W/@34.133815,-118.394261,17z/data=!3m1!4b1!4m5!3m4!1s0x0:0x0!8m2!3d34.133815!4d-118.392067) is full of Tauroses. 

Just wanted to add that to the map, but unsure of how. Other than posting it here.

**Comment by nyeung01** [comment]
To add a Pokemon site, just hold down the left click on the area of the map, and an option for you to add a Pokemon will appear.

**Comment by BMOv2600** [comment]
Thank you. Is this just common knowledge?

**Comment by nyeung01** [comment]
Pretty much. It's on the introduction window when the map is finished loading.
