### ISSUE TITLE
Remove data from non official sources

### ISSUE THREAD

**Issue by pablohpsilva** [felipefrancisco/pokemon-go-map#4]
So... I'm Brazilian. That means that are a bunch of sons of bitches messing up with your amazing tool. They are registering pokemons in my country, but the reality is that pokemon go wasn't launched here yet.

Following the @PokemonGoApp account on twitter, you'll find that only Japan, New Zeland, Australia, USA, Germany and UK have pokemons for real.

**Comment by felipefrancisco** [comment]
Thanks @pablohenrique! I've cleaned all pokemons placed on Brazil.
Although the official launch was made on these countries only, many players are being able to play in different country, I was planning to lock the pokemon placement only on these regions, but this would prevent player who are actually playing the game on other countries to add new pokemon to the map  :( (this would be my case).

Maybe I can develop a moderation system.

**Comment by pablohpsilva** [comment]
@felipefrancisco Do you know if its possible to get the marker location and see where its gonna be placed?
If you can do it, you won't need a moderation system. Just get the country name and compare it against an array of countries that has pokemon go available.

**Comment by felipefrancisco** [comment]
I've deployed the Reporting system now, but I'll work on that, i think it's not that complicated to create.

Thanks!
