### ISSUE TITLE
Suggestion: Valoration/Confirmation for each Pokemon

### ISSUE THREAD

**Issue by caito103** [felipefrancisco/pokemon-go-map#5]
As a suggestion, maybe you can put for each Pokemon in the map a Ranking style mod, so the people can select if the information of a specific Pokemon is true or not, and if a pokemon have a determinated number of votes that the information is false, remove it from the map. If you need help programming or something, do not hesitate to contact me. :)

**Comment by felipefrancisco** [comment]
Thanks! Will work on a ranking/reporting system asap.

Thanks for all support!

**Comment by felipefrancisco** [comment]
Duplicate of https://github.com/felipefrancisco/pokemon-go-map/issues/4
