### ISSUE TITLE
Suggestion: Add pokestops and gyms, Get rid of circles around pokemon

### ISSUE THREAD

**Issue by bmarshall645** [felipefrancisco/pokemon-go-map#6]
So I have a couple suggestions for this map. I think we should be able to add pokestops and gyms somehow to this map (Maybe pokestops could be represented with a blue pin and gyms can be represented with a pokeball).

My next suggestion is to possibly remove the circles around the pokemon when you mark one down on the map. I have seen multiple pokemon that spawn in the same area where I live and on the map you cant mark a new pokemon down where there is already a circle (Have to click an area outside the circle).

**Comment by felipefrancisco** [comment]
Great, I'll build a separated view to add pokestops and gyms, thanks :)

Wouldn't it be better if users could add more pokemon inside the circles rather than get rid of the circled area? I can work on that.

**Comment by bmarshall645** [comment]
How will we be able to access the pokestop and gym section of the map?
