### ISSUE TITLE
Google sign in gives 400 Error

### ISSUE THREAD

**Issue by strider1551** [felipefrancisco/pokemon-go-map#8]
Quickest response I think I have ever seen to an issue (resolving  #7). Just tried to login with Google and received a 400 Error:

> Error: redirect_uri_mismatch
> 
> Application: PokemonGOWorldMap
> 
> You can email the developer of this application at: --
> 
> The JavaScript origin in the request, http://pokemon-map.com, does not match the ones authorized for the OAuth client. Visit https://console.developers.google.com/apis/credentials/oauthclient/960529190271-8n3efjq2ac0d089e1m2mp9urdfkphh9e.apps.googleusercontent.com?project=960529190271 to update the authorized JavaScript origins.
> 
> Learn more
> 
> Request Details
> openid.realm=
> scope=email profile openid
> response_type=permission
> redirect_uri=storagerelay://http/pokemon-map.com?id=auth939476
> ss_domain=http://pokemon-map.com
> client_id=960529190271-8n3efjq2ac0d089e1m2mp9urdfkphh9e.apps.googleusercontent.com
> fetch_basic_profile=true

**Comment by felipefrancisco** [comment]
Can you try again now, please? Just modified some stuff, thanks for reporting.

**Comment by strider1551** [comment]
Yes, can confirm that Google sign is now works correctly.
