### ISSUE TITLE
Is it okay to make a copy of locations returned by your API?

### ISSUE THREAD

**Issue by kaetemi** [felipefrancisco/pokemon-go-map#9]
Hi, I'm making my own (yet another one) locations API (will be publicly documented). Is it okay to scrape this API http://www.pokemon-map.com/api/markers for location data to synchronize? Trying to get the data from all the different services together.

**Comment by felipefrancisco** [comment]
The map information is not completely accurate now, I suggest you to do this after I launch the final version with the "reporting" system.

**Comment by kaetemi** [comment]
Sure. I'm just testing things for now, so I just need some test data to get started. :)

**Comment by felipefrancisco** [comment]
I'm creating an consumer service provider, I recommend you to wait for it, I'll let you know when it's ready, then I can send you an API key to consume this properly.

**Comment by kaetemi** [comment]
Sounds cool. I'm just experimenting a little with geographical database queries right now, so needed some data. Doing some tests at http://pkloc.kaetemi.com/maps using a lowly populated world layer and geographical queries on the full data set when zoomed in. :)

**Comment by felipefrancisco** [comment]
@kaetemi I'd like to talk with you about your project, can you send me your e-mail or fb account, so we can have a quick chat? :)

**Comment by kaetemi** [comment]
Sure. Facebook account: kaetemi
